package com.permieware.osmapdigger.presentation

import com.permieware.osmapdigger.error.OperationalFailureKind


/** Languages supported by the shared application UI. Dataset-provided metric text remains dataset-owned. */
enum class UiLanguage(val code: String, val displayName: String) {
    RUSSIAN("ru", "Русский"),
    ENGLISH("en", "English"),
}

/** Localized application chrome used by shared Android/Desktop Compose surfaces. */
data class UiStrings(
    val language: UiLanguage,
    val languageLabel: String,
    val loadingDataset: String,
    val noDatasetInstalled: String,
    val generateAndImportDataset: String,
    val importDataset: String,
    val changeDataset: String,
    val candidateSource: String,
    val candidateSourceDataset: String,
    val candidateSourceImported: (Int) -> String,
    val candidateSourceImportedDisabled: (Int) -> String,
    val importSettlementList: String,
    val replaceSettlementList: String,
    val activateImportedCandidates: String,
    val deactivateImportedCandidates: String,
    val clearImportedList: String,
    val settlementListImportTitle: String,
    val settlementListImportInstructions: String,
    val importReviewUsesRadius: (String, Double) -> String,
    val settlementListTextLabel: String,
    val loadTextFile: String,
    val resolveNames: String,
    val resolvingNames: String,
    val importResolvedSummary: (Int, Int) -> String,
    val exactMatch: String,
    val ambiguousMatch: String,
    val selectAll: String,
    val clearSelection: String,
    val noExactMatch: String,
    val suggestions: String,
    val skipEntry: String,
    val applyImportedCandidates: (Int) -> String,
    val noImportLines: String,
    val generatedSearchQuery: String,
    val searchTab: String,
    val mapTab: String,
    val searching: String,
    val searchSettlements: String,
    val foundSettlements: (Int) -> String,
    val population: (Long) -> String,
    val searchAreaOptional: String,
    val center: (String) -> String,
    val centerSettlementOptional: String,
    val findCenter: String,
    val cancelCenterPick: String,
    val pickCenterOnMap: String,
    val mapPickHint: String,
    val useAsCenter: (String) -> String,
    val radiusOptional: String,
    val selectCenterFirst: String,
    val zeroRadiusHint: String,
    val clear: String,
    val filters: String,
    val required: String,
    val addFilter: String,
    val addRequiredFilter: String,
    val chooseRequiredMetric: String,
    val close: String,
    val allRequiredMetricsUsed: String,
    val remove: String,
    val preferences: String,
    val noPreferenceDefaults: String,
    val weight: (Int) -> String,
    val resetDatasetDefault: String,
    val rankedResults: String,
    val favorites: String,
    val favoriteCount: (Int) -> String,
    val addToFavorites: String,
    val openFavorites: String,
    val clearFavorites: String,
    val favoritesEmpty: String,
    val openFavorite: String,
    val favoriteUnavailable: String,
    val selectedFavorites: (Int) -> String,
    val copyFavoritesToImport: (Int) -> String,
    val batchExternalSearchHint: String,
    val noBatchExternalProviders: String,
    val favoriteCurrentAnalysis: (Int?, Int?, Int, Boolean) -> String,
    val favoriteNotInCurrentResults: String,
    val favoriteCurrentSelection: String,
    val favoriteNote: String,
    val editFavoriteNote: String,
    val saveFavoriteNote: String,
    val cancelFavoriteNote: String,
    val noFavoriteSnapshot: String,
    val favoriteSnapshotSummary: (Int?, Int, Boolean) -> String,
    val favoriteSnapshotRequired: String,
    val favoriteSnapshotPreferences: String,
    val updateFavoriteSnapshot: String,
    val dataCoverage: (Int) -> String,
    val selected: String,
    val searchResults: String,
    val settlementsFound: (Int) -> String,
    val coordinates: (String, String) -> String,
    val updating: String,
    val details: String,
    val externalSearch: String,
    val externalSearchSettings: String,
    val datasetSearchTerms: (String) -> String,
    val externalSearchTermsHint: String,
    val setDefaultSearchTerms: String,
    val customSearchTerms: String,
    val emptyCustomSearchTermsHint: String,
    val saveSearchSettings: String,
    val activeCriteria: String,
    val summary: String,
    val score: String,
    val scoreValue: (Int?) -> String,
    val scoreUnavailable: String,
    val scoreAndCoverage: (Int, Int) -> String,
    val strongest: String,
    val weakest: String,
    val unknown: String,
    val unknownValue: String,
    val unknownContribution: String,
    val points: (String) -> String,
    val noExternalProviders: String,
    val settlementDetails: String,
    val externalPropertySearch: String,
    val loadingMap: String,
    val noGeneratedMap: String,
    val mapUnavailable: String,
    val mapUnavailableExplanation: String,
    val dataset: (String) -> String,
    val resultsInCurrentSearch: (Int) -> String,
    val selectedSettlement: (String, Double, Double) -> String,
    val noGeneratedMapArtifact: String,
    val radiusRequiresCenter: String,
    val radiusInvalid: String,
    val operationalFailureMessage: (OperationalFailureKind) -> String,
    val minDistance: String,
    val maxDistance: String,
    val minNumber: String,
    val maxNumber: String,
    val minCoverage: String,
    val maxCoverage: String,
    val minValue: String,
    val maxValue: String,
    val nearestMappedFeature: (String) -> String,
    val mappedFeaturesInFixedRadius: String,
    val mappedAreaCoverage: (String) -> String,
    val bestLower: String,
    val bestHigher: String,
    val target: String,
    val zeroHigher: String,
    val zeroLower: String,
    val limit: String,
    val notScoreable: String,
    val lowerThresholdError: String,
    val higherThresholdError: String,
    val neutralThresholdError: String,
    val bestLowerSummary: (String, String) -> String,
    val bestHigherSummary: (String, String) -> String,
    val noFiltersSummary: String,
    val findSettlementsPrefix: String,
    val withinCenter: (String, String) -> String,
    val aroundCenter: (String) -> String,
    val atLeast: (String) -> String,
    val upTo: (String) -> String,
)

object UiLocalization {
    val defaultLanguage: UiLanguage = UiLanguage.RUSSIAN

    fun strings(language: UiLanguage): UiStrings = when (language) {
        UiLanguage.RUSSIAN -> RussianUiStrings
        UiLanguage.ENGLISH -> EnglishUiStrings
    }
}

private val RussianUiStrings = UiStrings(
    language = UiLanguage.RUSSIAN,
    languageLabel = "Язык",
    loadingDataset = "Загрузка набора данных…",
    noDatasetInstalled = "Локальный набор данных не установлен.",
    generateAndImportDataset = "Создайте .omd.zip с помощью Python Geo Builder и импортируйте его сюда.",
    importDataset = "Импортировать набор",
    changeDataset = "Сменить",
    candidateSource = "Источник кандидатов",
    candidateSourceDataset = "Весь набор данных",
    candidateSourceImported = { count -> "Импортированный список активен: $count" },
    candidateSourceImportedDisabled = { count -> "Импортированный список отключён: $count" },
    importSettlementList = "Импортировать список",
    replaceSettlementList = "Изменить список",
    activateImportedCandidates = "Включить импорт",
    deactivateImportedCandidates = "Отключить импорт",
    clearImportedList = "Удалить сохранённый список",
    settlementListImportTitle = "Импорт населённых пунктов",
    settlementListImportInstructions = "Вставьте список или загрузите UTF-8 текстовый файл: один населённый пункт на строку. Неоднозначные и неточные совпадения требуют явного выбора.",
    importReviewUsesRadius = { center, radius -> "Варианты ограничены текущей областью: $center, радиус ${NumberFormatter.compact(radius)} км." },
    settlementListTextLabel = "Названия населённых пунктов",
    loadTextFile = "Загрузить .txt",
    resolveNames = "Проверить названия",
    resolvingNames = "Проверка…",
    importResolvedSummary = { resolved, total -> "Выбрано кандидатов: $resolved из $total строк" },
    exactMatch = "Точное совпадение",
    ambiguousMatch = "Несколько точных совпадений — выберите один, несколько или все",
    selectAll = "Выбрать всех",
    clearSelection = "Снять выбор",
    noExactMatch = "Точного совпадения нет",
    suggestions = "Возможные варианты",
    skipEntry = "Пропустить строку",
    applyImportedCandidates = { count -> "Использовать кандидатов: $count" },
    noImportLines = "Добавьте хотя бы одно название населённого пункта.",
    generatedSearchQuery = "Условия поиска",
    searchTab = "Поиск",
    mapTab = "Карта",
    searching = "Поиск…",
    searchSettlements = "Найти населённые пункты",
    foundSettlements = { count -> "Найдено населённых пунктов: $count" },
    population = { value -> "население $value" },
    searchAreaOptional = "Область поиска (необязательно)",
    center = { name -> "Центр: $name ×" },
    centerSettlementOptional = "Населённый пункт-центр (необязательно)",
    findCenter = "Найти центр",
    cancelCenterPick = "Отменить выбор центра",
    pickCenterOnMap = "Выбрать центр на карте",
    mapPickHint = "Нажмите в любом месте карты. Ближайший населённый пункт станет центром поиска; выбранный результат не изменится.",
    useAsCenter = { name -> "Использовать $name как центр" },
    radiusOptional = "Радиус от центра, км (необязательно)",
    selectCenterFirst = "Сначала выберите населённый пункт-центр.",
    zeroRadiusHint = "0 означает отсутствие ограничения по радиусу.",
    clear = "Очистить",
    filters = "Фильтры",
    required = "Обязательные условия",
    addFilter = "Добавить фильтр",
    addRequiredFilter = "Добавить обязательный фильтр",
    chooseRequiredMetric = "Выберите метрику для жёсткого условия отбора.",
    close = "Закрыть",
    allRequiredMetricsUsed = "Все доступные метрики уже используются как обязательные фильтры.",
    remove = "Удалить",
    preferences = "Предпочтения",
    noPreferenceDefaults = "Для этого набора данных не заданы предпочтения. Обязательные условия остаются доступными.",
    weight = { value -> "Вес $value" },
    resetDatasetDefault = "Вернуть значение набора данных",
    rankedResults = "Результаты по рейтингу",
    favorites = "Избранное",
    favoriteCount = { count -> "В избранном: $count" },
    addToFavorites = "В избранное",
    openFavorites = "Открыть избранное",
    clearFavorites = "Очистить избранное",
    favoritesEmpty = "Избранное пока пусто.",
    openFavorite = "Открыть",
    favoriteUnavailable = "Населённый пункт отсутствует в текущей версии набора данных.",
    selectedFavorites = { count -> "Выбрано: $count" },
    copyFavoritesToImport = { count -> "Скопировать в импорт-список ($count)" },
    batchExternalSearchHint = "Каждый сформированный запрос открывается только по отдельному нажатию.",
    noBatchExternalProviders = "Для выбранных пунктов нет сервисов, поддерживающих пакетный поиск.",
    favoriteCurrentAnalysis = { rank, score, coverage, hasScoring ->
        val scoring =
            if (!hasScoring) {
                null
            } else {
                score?.let { value -> if (coverage < 100) "оценка $value · полнота $coverage%" else "оценка $value" }
                    ?: "оценка недоступна"
            }
        listOfNotNull(rank?.let { "рейтинг #$it" }, scoring).joinToString(" · ")
    },
    favoriteNotInCurrentResults = "Не соответствует текущим условиям анализа.",
    favoriteCurrentSelection = "Текущий",
    favoriteNote = "Заметка",
    editFavoriteNote = "Заметка",
    saveFavoriteNote = "Сохранить заметку",
    cancelFavoriteNote = "Отмена",
    noFavoriteSnapshot = "Снимок анализа ещё не сохранён.",
    favoriteSnapshotSummary = { score, coverage, hasScoring ->
        val scoring =
            if (!hasScoring) null
            else score?.let { value -> if (coverage < 100) "оценка $value · полнота $coverage%" else "оценка $value" }
                ?: "оценка недоступна"
        listOfNotNull("Сохранённый анализ", scoring).joinToString(": ")
    },
    favoriteSnapshotRequired = "Обязательные условия",
    favoriteSnapshotPreferences = "Предпочтения",
    updateFavoriteSnapshot = "Обновить",
    dataCoverage = { value -> "Полнота данных $value%" },
    selected = "Выбрано",
    searchResults = "Результаты поиска",
    settlementsFound = { count -> if (count == 1) "Найден 1 населённый пункт" else "Найдено населённых пунктов: $count" },
    coordinates = { latitude, longitude -> "Координаты: $latitude, $longitude" },
    updating = "обновление…",
    details = "Подробнее",
    externalSearch = "Внешний поиск",
    externalSearchSettings = "Настройки внешнего поиска",
    datasetSearchTerms = { terms -> "Слова набора данных: ${terms.ifBlank { "—" }}" },
    externalSearchTermsHint = "В поле каждого сервиса указаны дополнительные слова, которые будут добавлены к запросу. Очистите поле, если они не нужны, и нажмите «Сохранить настройки поиска».",
    setDefaultSearchTerms = "Установить дефолтные",
    customSearchTerms = "Дополнительные слова поиска",
    emptyCustomSearchTermsHint = "Оставьте пустым, чтобы ничего не добавлять.",
    saveSearchSettings = "Сохранить настройки поиска",
    activeCriteria = "Активные критерии",
    summary = "Кратко",
    score = "Оценка",
    scoreValue = { value -> value?.let { "Оценка $it" } ?: "Оценка —" },
    scoreUnavailable = "Оценка недоступна",
    scoreAndCoverage = { value, coverage -> if (coverage < 100) "Оценка $value · полнота $coverage%" else "Оценка $value" },
    strongest = "Сильнейший вклад",
    weakest = "Слабейший вклад",
    unknown = "Нет данных",
    unknownValue = "нет данных",
    unknownContribution = "вклад неизвестен",
    points = { value -> "+$value балл." },
    noExternalProviders = "Для этого набора данных не настроены внешние поисковые сервисы.",
    settlementDetails = "Подробности населённого пункта",
    externalPropertySearch = "Внешний поиск недвижимости",
    loadingMap = "Загрузка карты…",
    noGeneratedMap = "В этом пакете нет сгенерированной карты.",
    mapUnavailable = "Карта недоступна на этой Desktop-платформе",
    mapUnavailableExplanation = "Для этой ОС/архитектуры не настроен нативный MapLibre Compose. Поиск, фильтры, данные населённых пунктов и набор данных остаются доступными.",
    dataset = { name -> "Набор данных: $name" },
    resultsInCurrentSearch = { count -> "Результатов текущего поиска: $count" },
    selectedSettlement = { name, lat, lon -> "Выбрано: $name ($lat, $lon)" },
    noGeneratedMapArtifact = "В установленном пакете также отсутствует сгенерированный файл карты.",
    radiusRequiresCenter = "Перед заданием радиуса выберите населённый пункт-центр.",
    radiusInvalid = "Радиус должен быть равен нулю или быть положительным числом.",
    operationalFailureMessage = { kind ->
        when (kind) {
            OperationalFailureKind.DATASET_NOT_FOUND -> "Набор данных не найден."
            OperationalFailureKind.DATASET_INVALID -> "Пакет набора данных повреждён или несовместим."
            OperationalFailureKind.DATASET_STORAGE -> "Не удалось прочитать или сохранить файлы набора данных."
            OperationalFailureKind.FILE_ACCESS -> "Не удалось прочитать выбранный локальный файл."
            OperationalFailureKind.DATABASE -> "Не удалось прочитать локальные аналитические данные."
            OperationalFailureKind.SETTINGS -> "Не удалось прочитать или сохранить локальные настройки."
            OperationalFailureKind.SETTINGS_INCOMPATIBLE -> "Локальная база настроек имеет неподдерживаемую версию."
            OperationalFailureKind.EXTERNAL_ACTION -> "Не удалось открыть внешнее действие."
            OperationalFailureKind.MAP -> "Не удалось запустить локальную карту."
            OperationalFailureKind.UNKNOWN -> "Произошла непредвиденная локальная ошибка."
        }
    },
    minDistance = "Мин. расстояние",
    maxDistance = "Макс. расстояние",
    minNumber = "Мин. количество",
    maxNumber = "Макс. количество",
    minCoverage = "Мин. покрытие",
    maxCoverage = "Макс. покрытие",
    minValue = "Мин. значение",
    maxValue = "Макс. значение",
    nearestMappedFeature = { suffix -> "Расстояние до ближайшего объекта на карте$suffix" },
    mappedFeaturesInFixedRadius = "Количество объектов на карте внутри фиксированного радиуса этой метрики",
    mappedAreaCoverage = { suffix -> "Доля площади, покрытая объектами на карте$suffix" },
    bestLower = "Лучшее ≤",
    bestHigher = "Лучшее ≥",
    target = "Цель",
    zeroHigher = "Ноль ≥",
    zeroLower = "Ноль ≤",
    limit = "Предел",
    notScoreable = "не участвует в рейтинге",
    lowerThresholdError = "Лучший порог должен быть меньше порога нулевого вклада.",
    higherThresholdError = "Лучший порог должен быть больше порога нулевого вклада.",
    neutralThresholdError = "Для нейтральной метрики нужно явно задать направление оценки.",
    bestLowerSummary = { target, limit -> "лучшее ≤ $target · ноль ≥ $limit" },
    bestHigherSummary = { target, limit -> "лучшее ≥ $target · ноль ≤ $limit" },
    noFiltersSummary = "Фильтры не заданы: показываются населённые пункты текущего набора данных.",
    findSettlementsPrefix = "Найти населённые пункты",
    withinCenter = { radius, center -> "в радиусе $radius км от $center" },
    aroundCenter = { center -> "вокруг $center" },
    atLeast = { value -> "не менее $value" },
    upTo = { value -> "не более $value" },
)

private val EnglishUiStrings = UiStrings(
    language = UiLanguage.ENGLISH,
    languageLabel = "Language",
    loadingDataset = "Loading dataset…",
    noDatasetInstalled = "No local dataset is installed.",
    generateAndImportDataset = "Generate a .omd.zip with the Python Geo Builder, then import it here.",
    importDataset = "Import dataset",
    changeDataset = "Change",
    candidateSource = "Candidate source",
    candidateSourceDataset = "Full dataset",
    candidateSourceImported = { count -> "Imported list active: $count" },
    candidateSourceImportedDisabled = { count -> "Imported list disabled: $count" },
    importSettlementList = "Import settlement list",
    replaceSettlementList = "Edit list",
    activateImportedCandidates = "Enable import",
    deactivateImportedCandidates = "Disable import",
    clearImportedList = "Delete saved list",
    settlementListImportTitle = "Import settlements",
    settlementListImportInstructions = "Paste a list or load a UTF-8 text file: one settlement per line. Ambiguous and non-exact matches require an explicit choice.",
    importReviewUsesRadius = { center, radius -> "Matches are limited to the current search area: $center, ${NumberFormatter.compact(radius)} km radius." },
    settlementListTextLabel = "Settlement names",
    loadTextFile = "Load .txt",
    resolveNames = "Review names",
    resolvingNames = "Reviewing…",
    importResolvedSummary = { resolved, total -> "Selected candidates: $resolved from $total lines" },
    exactMatch = "Exact match",
    ambiguousMatch = "Multiple exact matches — choose one, several, or all",
    selectAll = "Select all",
    clearSelection = "Clear selection",
    noExactMatch = "No exact match",
    suggestions = "Suggestions",
    skipEntry = "Skip line",
    applyImportedCandidates = { count -> "Use $count candidates" },
    noImportLines = "Add at least one settlement name.",
    generatedSearchQuery = "Generated search query",
    searchTab = "Search",
    mapTab = "Map",
    searching = "Searching…",
    searchSettlements = "Search settlements",
    foundSettlements = { count -> "Found settlements ($count)" },
    population = { value -> "population $value" },
    searchAreaOptional = "Search area (optional)",
    center = { name -> "Center: $name ×" },
    centerSettlementOptional = "Center settlement (optional)",
    findCenter = "Find center",
    cancelCenterPick = "Cancel center pick",
    pickCenterOnMap = "Pick center on map",
    mapPickHint = "Click anywhere on the map. The nearest settlement will become the search center; result selection will not change.",
    useAsCenter = { name -> "Use $name as center" },
    radiusOptional = "Radius from center, km (optional)",
    selectCenterFirst = "Select a center settlement first.",
    zeroRadiusHint = "0 means no radius limit.",
    clear = "Clear",
    filters = "Filters",
    required = "Required",
    addFilter = "Add filter",
    addRequiredFilter = "Add required filter",
    chooseRequiredMetric = "Choose a metric to add as a hard eligibility constraint.",
    close = "Close",
    allRequiredMetricsUsed = "All available metrics are already used as required filters.",
    remove = "Remove",
    preferences = "Preferences",
    noPreferenceDefaults = "This dataset has no preference defaults. Required constraints remain available.",
    weight = { value -> "Weight $value" },
    resetDatasetDefault = "Reset to dataset default",
    rankedResults = "Ranked results",
    favorites = "Favorites",
    favoriteCount = { count -> "Favorites: $count" },
    addToFavorites = "Favorite",
    openFavorites = "Open favorites",
    clearFavorites = "Clear favorites",
    favoritesEmpty = "No favorites yet.",
    openFavorite = "Open",
    favoriteUnavailable = "This settlement is not available in the current dataset version.",
    selectedFavorites = { count -> "Selected: $count" },
    copyFavoritesToImport = { count -> "Copy to import list ($count)" },
    batchExternalSearchHint = "Each generated query opens only after an explicit click.",
    noBatchExternalProviders = "No configured provider supports batch search for this selection.",
    favoriteCurrentAnalysis = { rank, score, coverage, hasScoring ->
        val scoring =
            if (!hasScoring) {
                null
            } else {
                score?.let { value -> if (coverage < 100) "score $value · coverage $coverage%" else "score $value" }
                    ?: "score unavailable"
            }
        listOfNotNull(rank?.let { "rank #$it" }, scoring).joinToString(" · ")
    },
    favoriteNotInCurrentResults = "Does not match the current analysis criteria.",
    favoriteCurrentSelection = "Current",
    favoriteNote = "Note",
    editFavoriteNote = "Note",
    saveFavoriteNote = "Save note",
    cancelFavoriteNote = "Cancel",
    noFavoriteSnapshot = "No analysis snapshot has been saved yet.",
    favoriteSnapshotSummary = { score, coverage, hasScoring ->
        val scoring =
            if (!hasScoring) null
            else score?.let { value -> if (coverage < 100) "score $value · coverage $coverage%" else "score $value" }
                ?: "score unavailable"
        listOfNotNull("Saved analysis", scoring).joinToString(": ")
    },
    favoriteSnapshotRequired = "Required",
    favoriteSnapshotPreferences = "Preferences",
    updateFavoriteSnapshot = "Update",
    dataCoverage = { value -> "Data coverage $value%" },
    selected = "Selected",
    searchResults = "Search results",
    settlementsFound = { count -> if (count == 1) "1 settlement found" else "$count settlements found" },
    coordinates = { latitude, longitude -> "Coordinates: $latitude, $longitude" },
    updating = "updating…",
    details = "Details",
    externalSearch = "External search",
    externalSearchSettings = "External search settings",
    datasetSearchTerms = { terms -> "Dataset terms: ${terms.ifBlank { "—" }}" },
    externalSearchTermsHint = "Each provider field contains the extra terms added to its query. Clear the field when none are needed, then choose Save search settings.",
    setDefaultSearchTerms = "Set defaults",
    customSearchTerms = "Additional search terms",
    emptyCustomSearchTermsHint = "Leave empty to add nothing.",
    saveSearchSettings = "Save search settings",
    activeCriteria = "Active criteria",
    summary = "Summary",
    score = "Score",
    scoreValue = { value -> value?.let { "Score $it" } ?: "Score —" },
    scoreUnavailable = "Score unavailable",
    scoreAndCoverage = { value, coverage -> if (coverage < 100) "Score $value · coverage $coverage%" else "Score $value" },
    strongest = "Strongest",
    weakest = "Weakest",
    unknown = "Unknown",
    unknownValue = "unknown",
    unknownContribution = "unknown contribution",
    points = { value -> "+$value pts" },
    noExternalProviders = "No external search providers are configured for this dataset.",
    settlementDetails = "Settlement details",
    externalPropertySearch = "External property search",
    loadingMap = "Loading dataset…",
    noGeneratedMap = "This package has no generated map.",
    mapUnavailable = "Map unavailable on this Desktop host",
    mapUnavailableExplanation = "This OS/architecture has no MapLibre Compose native runtime configured by OsmapDigger. Search, filters, settlement details, and generated dataset data remain available.",
    dataset = { name -> "Dataset: $name" },
    resultsInCurrentSearch = { count -> "Results in current search: $count" },
    selectedSettlement = { name, lat, lon -> "Selected: $name ($lat, $lon)" },
    noGeneratedMapArtifact = "The installed package also has no generated map artifact.",
    radiusRequiresCenter = "Select a center settlement before setting a radius.",
    radiusInvalid = "Radius must be zero or a positive number.",
    operationalFailureMessage = { kind ->
        when (kind) {
            OperationalFailureKind.DATASET_NOT_FOUND -> "Dataset package was not found."
            OperationalFailureKind.DATASET_INVALID -> "The dataset package is damaged or incompatible."
            OperationalFailureKind.DATASET_STORAGE -> "Dataset files could not be read or stored."
            OperationalFailureKind.FILE_ACCESS -> "The selected local file could not be read."
            OperationalFailureKind.DATABASE -> "Local analytical data could not be read."
            OperationalFailureKind.SETTINGS -> "Local settings could not be read or saved."
            OperationalFailureKind.SETTINGS_INCOMPATIBLE -> "The local settings database has an unsupported version."
            OperationalFailureKind.EXTERNAL_ACTION -> "The external action could not be opened."
            OperationalFailureKind.MAP -> "The local map could not be started."
            OperationalFailureKind.UNKNOWN -> "An unexpected local error occurred."
        }
    },
    minDistance = "Min distance",
    maxDistance = "Max distance",
    minNumber = "Min number",
    maxNumber = "Max number",
    minCoverage = "Min coverage",
    maxCoverage = "Max coverage",
    minValue = "Min value",
    maxValue = "Max value",
    nearestMappedFeature = { suffix -> "Distance to the nearest mapped feature$suffix" },
    mappedFeaturesInFixedRadius = "Number of mapped features inside the fixed radius in this metric",
    mappedAreaCoverage = { suffix -> "Area share covered by mapped features$suffix" },
    bestLower = "Best ≤",
    bestHigher = "Best ≥",
    target = "Target",
    zeroHigher = "Zero ≥",
    zeroLower = "Zero ≤",
    limit = "Limit",
    notScoreable = "not scoreable",
    lowerThresholdError = "Best threshold must be lower than zero-contribution threshold.",
    higherThresholdError = "Best threshold must be higher than zero-contribution threshold.",
    neutralThresholdError = "Neutral metrics require an explicit scoreable direction.",
    bestLowerSummary = { target, limit -> "best ≤ $target · zero ≥ $limit" },
    bestHigherSummary = { target, limit -> "best ≥ $target · zero ≤ $limit" },
    noFiltersSummary = "No filters: show settlements from the current dataset.",
    findSettlementsPrefix = "Find settlements",
    withinCenter = { radius, center -> "within $radius km of $center" },
    aroundCenter = { center -> "around $center" },
    atLeast = { value -> "at least $value" },
    upTo = { value -> "up to $value" },
)
